language: go
go:
  - 1.8.3
  - tip
install:
  - go get -u -v -t ./...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
